name: Deploy React Landings

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Test SSH port 22
        run: nc -zv 64.227.99.126 22 || echo "SSH port 22 not reachable"

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 64.227.99.126 >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@v5.2
        with:
          switches: -avz --delete --timeout=60
          path: ./dist/
          remote_path: /var/www/html/ofplan/
          remote_host: 64.227.99.126
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_KEY }}