name: Deploy React Landings

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 64.227.99.126 >> ~/.ssh/known_hosts

      - name: Copy build to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 64.227.99.126
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          source: "dist/*"
          target: "/var/www/html/ofplan"
